/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package coolgle;

import java.awt.*;

/**
 *
 * @author rdg77_000
 */
public class mainGui extends javax.swing.JFrame {

    /**
     * Creates new form mainGui
     */
    public mainGui() {
              Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
		Dimension frm = super.getSize();
        	int xpos = (int) (screen.getWidth() / 8 - frm.getWidth() / 2);
		int ypos = (int) (screen.getHeight() / 30);
		super.setLocation(xpos,  ypos);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new javax.swing.JLabel();
        switchAdminBtn = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        welcomeLabel2 = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        clearSearchBtn = new javax.swing.JButton();
        selectLabel1 = new javax.swing.JLabel();
        selectLabel2 = new javax.swing.JLabel();
        selectLabel3 = new javax.swing.JLabel();
        prevList = new javax.swing.JComboBox();
        helpBtn = new javax.swing.JButton();
        orLabel = new javax.swing.JLabel();
        startLabel = new javax.swing.JLabel();
        startLabel2 = new javax.swing.JLabel();
        startLabel3 = new javax.swing.JLabel();
        locationText = new javax.swing.JTextField();
        timeLabel = new javax.swing.JLabel();
        startLoLabel = new javax.swing.JLabel();
        endLabel = new javax.swing.JLabel();
        midLabel = new javax.swing.JLabel();
        midLocationText = new javax.swing.JTextField();
        endLocationText = new javax.swing.JTextField();
        times = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        mapItBtn = new javax.swing.JButton();
        startTimeLabel = new javax.swing.JLabel();
        startLocationLabel = new javax.swing.JLabel();
        midLocationLabel = new javax.swing.JLabel();
        endLocationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label2.setText("<html>\nThe list of locations chosen is shown <br>\non the right panel, click Map It to <br>\nshow it on Google Earth!\n</html>");

        switchAdminBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\rdg77_000\\Documents\\classes\\cmsc345\\output\\output\\switch_to_admin_button.jpg")); // NOI18N

        label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label1.setText("<html>\nEnter the location information below <br>\nand we will show you the way!\n</html>");

        welcomeLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        welcomeLabel2.setForeground(new java.awt.Color(153, 0, 0));
        welcomeLabel2.setText("Coolgles ");

        welcomeLabel.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        welcomeLabel.setText("Welcome to");

        clearSearchBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\rdg77_000\\Documents\\classes\\cmsc345\\output\\output\\clear_search_button.jpg")); // NOI18N

        selectLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        selectLabel1.setText("Select");

        selectLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        selectLabel2.setForeground(new java.awt.Color(102, 0, 0));
        selectLabel2.setText("Previous");

        selectLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        selectLabel3.setText("Search");

        prevList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        helpBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\rdg77_000\\Documents\\classes\\cmsc345\\output\\output\\question_button.jpg")); // NOI18N
        helpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBtnActionPerformed(evt);
            }
        });

        orLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        orLabel.setText("- - - - - - - - - - - - - - - - - - OR - - - - - - - - - - - - - - - - - -");

        startLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        startLabel.setText("Start ");

        startLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        startLabel2.setForeground(new java.awt.Color(102, 0, 0));
        startLabel2.setText("New");

        startLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        startLabel3.setText("Search");

        locationText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        locationText.setToolTipText("");
        locationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTextActionPerformed(evt);
            }
        });

        timeLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        timeLabel.setText("Start Time: ");

        startLoLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        startLoLabel.setText("Start Location: ");

        endLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        endLabel.setText("End Location: ");

        midLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        midLabel.setText("Mid Locations: ");

        midLocationText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        midLocationText.setToolTipText("");
        midLocationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midLocationTextActionPerformed(evt);
            }
        });

        endLocationText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        endLocationText.setToolTipText("");
        endLocationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endLocationTextActionPerformed(evt);
            }
        });

        times.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        times.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "08:00 am", "09:00 am", "10:00 am", "11:00 am", "12:00 pm", "01:00 pm", "02:00 pm", "03:00 pm", "04:00 pm", "05:00 pm", "06:00 pm", "07:00 pm", "08:00 pm", "09:00 pm", " " }));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        mapItBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\rdg77_000\\Documents\\classes\\cmsc345\\output\\output\\map_it_button.jpg")); // NOI18N
        mapItBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapItBtnActionPerformed(evt);
            }
        });

        startTimeLabel.setBackground(new java.awt.Color(255, 255, 255));
        startTimeLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        startTimeLabel.setText("Start Time");

        startLocationLabel.setBackground(new java.awt.Color(255, 255, 255));
        startLocationLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        startLocationLabel.setText("Start Location");

        midLocationLabel.setBackground(new java.awt.Color(255, 255, 255));
        midLocationLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        midLocationLabel.setText("Mid Location");

        endLocationLabel.setBackground(new java.awt.Color(255, 255, 255));
        endLocationLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        endLocationLabel.setText("End Location");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(mapItBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(startLocationLabel)
                            .addComponent(endLocationLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(startTimeLabel)
                                .addGap(9, 9, 9))
                            .addComponent(midLocationLabel))
                        .addGap(211, 211, 211))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startTimeLabel)
                .addGap(56, 56, 56)
                .addComponent(startLocationLabel)
                .addGap(54, 54, 54)
                .addComponent(midLocationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(endLocationLabel)
                .addGap(94, 94, 94)
                .addComponent(mapItBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(orLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(selectLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(69, 69, 69)
                                    .addComponent(prevList, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(helpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(selectLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(selectLabel3)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(startLoLabel)
                                    .addComponent(timeLabel)
                                    .addComponent(midLabel)
                                    .addComponent(endLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(midLocationText)
                                    .addComponent(endLocationText)
                                    .addComponent(times, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(locationText, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(welcomeLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(clearSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(switchAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(welcomeLabel2)
                            .addComponent(welcomeLabel))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(switchAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectLabel1)
                            .addComponent(selectLabel3)
                            .addComponent(selectLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prevList, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(orLabel)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startLabel)
                            .addComponent(startLabel2)
                            .addComponent(startLabel3))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeLabel)
                            .addComponent(times, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startLoLabel)
                            .addComponent(locationText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endLocationText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endLabel))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(midLocationText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(midLabel))
                        .addGap(0, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpBtnActionPerformed

    private void locationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationTextActionPerformed

    private void midLocationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midLocationTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midLocationTextActionPerformed

    private void endLocationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endLocationTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endLocationTextActionPerformed

    private void mapItBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapItBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mapItBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearSearchBtn;
    private javax.swing.JLabel endLabel;
    private javax.swing.JLabel endLocationLabel;
    private javax.swing.JTextField endLocationText;
    private javax.swing.JButton helpBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JTextField locationText;
    private javax.swing.JButton mapItBtn;
    private javax.swing.JLabel midLabel;
    private javax.swing.JLabel midLocationLabel;
    private javax.swing.JTextField midLocationText;
    private javax.swing.JLabel orLabel;
    private javax.swing.JComboBox prevList;
    private javax.swing.JLabel selectLabel1;
    private javax.swing.JLabel selectLabel2;
    private javax.swing.JLabel selectLabel3;
    private javax.swing.JLabel startLabel;
    private javax.swing.JLabel startLabel2;
    private javax.swing.JLabel startLabel3;
    private javax.swing.JLabel startLoLabel;
    private javax.swing.JLabel startLocationLabel;
    private javax.swing.JLabel startTimeLabel;
    private javax.swing.JButton switchAdminBtn;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JComboBox times;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel welcomeLabel2;
    // End of variables declaration//GEN-END:variables
}
