/*****************************************
 ** File: Search
 ** Team Name: Cava++
 *Date: 10/18/13
 ** E-mail: Daniel Brandes bradan1@umbc.edu,
 ** Lizset Chavez <lizset1@umbc.edu>
 ** Patrick Ritchie <ritc1@umbc.edu>,
 ** Xiaofei He <xiaofei2@umbc.edu>,
 ** Yo-Han Kim <ykim18@umbc.edu>,
 ** Jim Millican <jmill1@umbc.edu>
 ** Decription- Code behind the sign up gui.
 *Sign up gui should only be called from the sign in gui 
 ***********************************************/
package coolgle;

import java.awt.*;
import javax.swing.JOptionPane;

public class SignUpGui extends javax.swing.JFrame 
{
	private static int USER_MAX_LEN = 25; 

        // Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel emailLabel;
	private javax.swing.JTextField emailText;
	private javax.swing.JLabel signupLbl;
	private javax.swing.JLabel coolglesLbl;
	private javax.swing.JLabel accountLbl;
	private javax.swing.JLabel logoLabel;
	private javax.swing.JLabel pswdLabel;
	private javax.swing.JPasswordField pswdText;
	private javax.swing.JLabel rePswdLabel;
	private javax.swing.JPasswordField repswdText;
	private javax.swing.JButton submitBtn;
	private javax.swing.JLabel userLabel;
	private javax.swing.JTextField usrnameText;
	// End of variables declaration//GEN-END:variables
	/**
	 *Constructor Creates new form SignUp
	 */
	public SignUpGui() 
	{
		Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
		Dimension frm = super.getSize();
		int xpos = (int) (screen.getWidth() / 8 - frm.getWidth() / 2);
		int ypos = (int) (screen.getHeight() / 8 - frm.getHeight() / 2);
		super.setLocation(xpos,  ypos);

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * Description-initializes components
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		logoLabel = new javax.swing.JLabel();
		signupLbl = new javax.swing.JLabel();
		accountLbl = new javax.swing.JLabel();
		coolglesLbl = new javax.swing.JLabel();
		pswdLabel = new javax.swing.JLabel();
		rePswdLabel = new javax.swing.JLabel();
		emailLabel = new javax.swing.JLabel();
		emailText = new javax.swing.JTextField();
		usrnameText = new javax.swing.JTextField();
		userLabel = new javax.swing.JLabel();
		submitBtn = new javax.swing.JButton();
		pswdText = new javax.swing.JPasswordField();
		repswdText = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		logoLabel.setIcon(new javax.swing.ImageIcon("Images\\logo.jpg")); // NOI18N

		signupLbl.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
		signupLbl.setText("Sign up for your own");

		accountLbl.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
		accountLbl.setText("Account");

		coolglesLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		coolglesLbl.setForeground(new java.awt.Color(102, 0, 0));
		coolglesLbl.setText("Coolgles");

		pswdLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		pswdLabel.setText("Password: ");

		rePswdLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		rePswdLabel.setText("Re-enter Password: ");

		emailLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		emailLabel.setText("Email: ");

		

		userLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		userLabel.setText("Username: ");

		submitBtn.setIcon(new javax.swing.ImageIcon("Images\\submit button.jpg")); // NOI18N
		submitBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				submitBtnActionPerformed(evt);
			}
		});
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(pswdLabel)
												.addComponent(userLabel)
												.addComponent(rePswdLabel)
												.addComponent(emailLabel))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
														.addComponent(emailText, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
														.addComponent(usrnameText, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
														.addComponent(pswdText)
														.addComponent(repswdText)))
														.addGroup(layout.createSequentialGroup()
																.addComponent(logoLabel)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(signupLbl)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(coolglesLbl)))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(accountLbl)
																.addContainerGap(15, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addContainerGap()
										.addComponent(logoLabel))
										.addGroup(layout.createSequentialGroup()
												.addGap(54, 54, 54)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(signupLbl)
														.addComponent(coolglesLbl)
														.addComponent(accountLbl))))
														.addGap(33, 33, 33)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(usrnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(userLabel))
																.addGap(18, 18, 18)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(pswdText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(pswdLabel))
																		.addGap(18, 18, Short.MAX_VALUE)
																		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(rePswdLabel)
																				.addComponent(repswdText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGap(18, 18, 18)
																				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(emailLabel))
																						.addGap(18, 18, 18)
																						.addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(48, 48, 48))
				);

		pack();
	}// </editor-fold>//GEN-END:initComponents




        
	/**
	 * submitBtnActionPerformed
	 * Description - Called when user presses the submit button
	 * Provides error messages if any of the following cases : 
	 * - Password fields are different 
	 * - Any field is empty 
	 * - Email does not contain "@" and "."
	 * - Username is already taken
	 * - Pass is under 2 chars long
	 * If no errors, creates the account and returns to the sign in screen. 
	 */
	private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) 
        {//GEN-FIRST:event_submitBtnActionPerformed
		UserAuthentication checkDups = new UserAuthentication();
		boolean nameTaken = checkDups.userExists(usrnameText.getText());
		if( new String(repswdText.getPassword()).compareTo( new String(pswdText.getPassword()) ) != 0 )
		{
			JOptionPane.showMessageDialog(null, "Ensure both passwords match", "Error", JOptionPane.ERROR_MESSAGE);
		}
		else if (emailText.getText().isEmpty() || usrnameText.getText().isEmpty() || 
				repswdText.getPassword().length == 0 || pswdText.getPassword().length == 0)
		{
			JOptionPane.showMessageDialog(null, "All fields must have data", "Error", JOptionPane.ERROR_MESSAGE);
		}
		else if( !(emailText.getText().contains("@") && emailText.getText().contains(".")) )
		{
			JOptionPane.showMessageDialog(null, "Email is not of correct format\n"
					+ "Ex : User@domain.com", "Error", JOptionPane.ERROR_MESSAGE);     
		}
		else if (repswdText.getPassword().length < 2)
		{
			JOptionPane.showMessageDialog(null, "Password must be at least 2 characters", "Error", JOptionPane.ERROR_MESSAGE); 
		}
                else if (usrnameText.getText().length() > USER_MAX_LEN)
		{
			JOptionPane.showMessageDialog(null, "Username must be under " + USER_MAX_LEN + " characters", "Error", JOptionPane.ERROR_MESSAGE); 
		}
		else if (nameTaken)
		{
			JOptionPane.showMessageDialog(null, "Name already taken", "Error", JOptionPane.ERROR_MESSAGE); 
		}
		else // Success 
		{
                        JOptionPane.showMessageDialog(this,"Account Successfully Created");
                    
                        UserAuthentication addUser = new UserAuthentication();
                        addUser.addUser(this.usrnameText.getText(), new String(this.pswdText.getPassword()), this.emailText.getText());

                        this.setVisible(false);
                        SignInGui signin = new SignInGui();
                        signin.setVisible(true);
                        
		}

	}//GEN-LAST:event_submitBtnActionPerformed


}
