/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package coolgle;

import java.awt.*;
import javax.swing.JOptionPane;

/**
 *
 * @author rdg77_000
 */
public class SignUpGui extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUpGui() {
              Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
		Dimension frm = super.getSize();
        		int xpos = (int) (screen.getWidth() / 8 - frm.getWidth() / 2);
		int ypos = (int) (screen.getHeight() / 8 - frm.getHeight() / 2);
		super.setLocation(xpos,  ypos);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        signupLbl = new javax.swing.JLabel();
        accountLbl = new javax.swing.JLabel();
        coolglesLbl = new javax.swing.JLabel();
        pswdLabel = new javax.swing.JLabel();
        rePswdLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        usrnameText = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        pswdText = new javax.swing.JPasswordField();
        repswdText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoLabel.setIcon(new javax.swing.ImageIcon("Images\\logo.jpg")); // NOI18N

        signupLbl.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        signupLbl.setText("Sign up for your own");

        accountLbl.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        accountLbl.setText("Account");

        coolglesLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        coolglesLbl.setForeground(new java.awt.Color(102, 0, 0));
        coolglesLbl.setText("Coolgles");

        pswdLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pswdLabel.setText("Password: ");

        rePswdLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rePswdLabel.setText("Re-enter Password: ");

        emailLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emailLabel.setText("Email: ");

        emailText.setToolTipText("");
        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });
        emailText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFocusGained(evt);
            }
        });

        usrnameText.setToolTipText("");
        usrnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrnameTextActionPerformed(evt);
            }
        });
        usrnameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usrnameTextFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                usrnameTextFocusGained(evt);
            }
        });

        userLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        userLabel.setText("Username: ");

        submitBtn.setIcon(new javax.swing.ImageIcon("Images\\submit button.jpg")); // NOI18N
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        pswdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdTextActionPerformed(evt);
            }
        });
        pswdText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswdTextFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                pswdTextFocusGained(evt);
            }
        });

        repswdText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                repswdTextFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                repswdTextFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pswdLabel)
                            .addComponent(userLabel)
                            .addComponent(rePswdLabel)
                            .addComponent(emailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailText, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(usrnameText, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(pswdText)
                            .addComponent(repswdText)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(signupLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coolglesLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountLbl)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(signupLbl)
                            .addComponent(coolglesLbl)
                            .addComponent(accountLbl))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswdText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswdLabel))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rePswdLabel)
                    .addComponent(repswdText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    private void usrnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrnameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrnameTextActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
      
      if(false){//!this.repswdText.getPassword().equals( this.pswdText.getPassword())){
          JOptionPane.showMessageDialog(null, "make sure to enter same passward");
      }else{
          //User ho = new User(this.usrnameText.getText(), this.pswdText.getPassword(), this.emailText.getText());
          this.setVisible(false);
          SignInGui signin = new SignInGui();
          signin.setVisible(true);
      }
      
    }//GEN-LAST:event_submitBtnActionPerformed

    private void pswdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdTextActionPerformed

    private void usrnameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usrnameTextFocusGained
        if(this.usrnameText.getText().equals("Enter your username"));
            this.usrnameText.setText("");
       
    }//GEN-LAST:event_usrnameTextFocusGained

    private void usrnameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usrnameTextFocusLost
       if(this.usrnameText.getText().equals(""))
      this.usrnameText.setText("Enter your username");
    }//GEN-LAST:event_usrnameTextFocusLost

    private void pswdTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswdTextFocusGained
     this.pswdText.setText("");
    }//GEN-LAST:event_pswdTextFocusGained

    private void pswdTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswdTextFocusLost
       if(this.pswdText.getPassword().equals(""))
        this.pswdText.setText("Enter8num");
    }//GEN-LAST:event_pswdTextFocusLost

    private void repswdTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_repswdTextFocusGained
    this.repswdText.setText("");
    }//GEN-LAST:event_repswdTextFocusGained

    private void repswdTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_repswdTextFocusLost
        if(this.repswdText.getPassword().equals(""))
            this.repswdText.setText("Enter8num");
    }//GEN-LAST:event_repswdTextFocusLost

    private void emailTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFocusGained
        if(this.emailText.getText().equals("Enter your email address"))
            this.emailText.setText("");
    }//GEN-LAST:event_emailTextFocusGained

    private void emailTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFocusLost
        if(this.emailText.getText().equals(""))
            this.emailText.setText("Enter your email address");
    }//GEN-LAST:event_emailTextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel signupLbl;
    private javax.swing.JLabel coolglesLbl;
    private javax.swing.JLabel accountLbl;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel pswdLabel;
    private javax.swing.JPasswordField pswdText;
    private javax.swing.JLabel rePswdLabel;
    private javax.swing.JPasswordField repswdText;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField usrnameText;
    // End of variables declaration//GEN-END:variables
}
