/*
 * Sign in form, this is the first thing the user sees
 */

package coolgle;
import java.awt.*;
import javax.swing.JOptionPane;
/**
 *
 * @author rdg77_000
 */
public class SignInGui extends javax.swing.JFrame 
{

    /**
     * Creates new form SignIn
     */
    public SignInGui() 
    {
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frm = super.getSize();
        int xpos = (int) (screen.getWidth() / 8 - frm.getWidth() / 2);
	int ypos = (int) (screen.getHeight() / 8 - frm.getHeight() / 2);
	super.setLocation(xpos,  ypos);
        
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpUpperImg = new javax.swing.JLabel();
        usrnameLabel = new javax.swing.JLabel();
        pswdLabel = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        logAdminCheck = new javax.swing.JCheckBox();
        signInBtn = new javax.swing.JButton();
        accountQuestionLabel = new javax.swing.JLabel();
        signUpBtn = new javax.swing.JButton();
        pswdText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signUpUpperImg.setIcon(new javax.swing.ImageIcon("Images\\logo_and_info.jpg")); // NOI18N

        usrnameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        usrnameLabel.setText("Username: ");

        pswdLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pswdLabel.setText("Password: ");

        usernameText.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        usernameText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });
        usernameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTextFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTextFocusGained(evt);
            }
        });

        logAdminCheck.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        logAdminCheck.setText("Log In as Administrator");
        logAdminCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logAdminCheckActionPerformed(evt);
            }
        });

        signInBtn.setIcon(new javax.swing.ImageIcon("Images\\sign_in_button.jpg")); // NOI18N
        signInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBtnActionPerformed(evt);
            }
        });

        accountQuestionLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        accountQuestionLabel.setText("Don't have an account?");

        signUpBtn.setIcon(new javax.swing.ImageIcon("Images\\sign_up_button.jpg")); // NOI18N
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });

        pswdText.setText("jPasswordField2");
        pswdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdTextActionPerformed(evt);
            }
        });
        pswdText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswdTextFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                pswdTextFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usrnameLabel)
                            .addComponent(pswdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(logAdminCheck)
                            .addComponent(usernameText, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(signInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pswdText)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accountQuestionLabel)
                        .addGap(18, 18, 18)
                        .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(signUpUpperImg, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(signUpUpperImg, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrnameLabel)
                    .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswdText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswdLabel))
                .addGap(18, 18, 18)
                .addComponent(logAdminCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountQuestionLabel))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextActionPerformed

    private void logAdminCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logAdminCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logAdminCheckActionPerformed

    private void pswdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdTextActionPerformed

    private void signInBtnActionPerformed(java.awt.event.ActionEvent evt) 
    {
        String un = this.usernameText.getText();
        char[] pass = this.pswdText.getPassword();
        boolean isAdmin = this.logAdminCheck.isSelected();
        int userType = isAdmin ? 1 : 0;
        
        //and check if it is valid
        UserAuthentication newAuthenicator = new UserAuthentication();
        boolean correctCredidentials = newAuthenicator.logUser(un, pass, userType); 
        
        if(correctCredidentials && this.logAdminCheck.isSelected()) 
        {// admin
             this.setVisible(false);
            adminGui admin = new adminGui();
            admin.setVisible(true);
        } 
        else if(correctCredidentials && this.logAdminCheck.isSelected() == false)
        {//User
            this.setVisible(false);
            mainGui user = new mainGui();
            user.setVisible(true);
        }
        else // Not correct Creds, show error message. 
        {
             JOptionPane.showMessageDialog(null, "User name and password are incorrect \n"
                                            + "Ensure all fields are correct including admin checkbox and try again\n"
                                            + "Sign up for a new acccount by clicking the Sign Up Here button\n\n"
                                            + "Note : Admins can reset passwords", "Invalid Login", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_signInBtnActionPerformed

    private void pswdTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswdTextFocusGained
  
        this.pswdText.setText("");
    }//GEN-LAST:event_pswdTextFocusGained

    private void pswdTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswdTextFocusLost
        if(this.pswdText.getPassword().equals(""))
        this.pswdText.setText("Enter8num");
    }//GEN-LAST:event_pswdTextFocusLost

    private void usernameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFocusGained
    if(this.usernameText.getText().equals("Enter your username"))
        this.usernameText.setText("");
    }//GEN-LAST:event_usernameTextFocusGained

    private void usernameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFocusLost
      
       if(this.usernameText.getText().equals(""))
      this.usernameText.setText("Enter your username");
    }//GEN-LAST:event_usernameTextFocusLost

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
    this.setVisible(false);
   SignUpGui ho = new SignUpGui();
    ho.setVisible(true);
    }//GEN-LAST:event_signUpBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountQuestionLabel;
    private javax.swing.JCheckBox logAdminCheck;
    private javax.swing.JLabel pswdLabel;
    private javax.swing.JPasswordField pswdText;
    private javax.swing.JButton signInBtn;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JLabel signUpUpperImg;
    private javax.swing.JTextField usernameText;
    private javax.swing.JLabel usrnameLabel;
    // End of variables declaration//GEN-END:variables
}
